### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by giangi007** [ThomasAndreini/Jarvis#5]
Ciao Thomas, scusa se ti faccio perdere tempo, ma non ho capito come fare a scaricare all'arduino mega tutti i file ino contenuti nel tuo file Jarvin-master.

Grazie per il tuo aiuto

**Comment by ThomasAndreini** [comment]
Devi aprire con l'editor il file Jarvis.ino avendo anche gli altri files
nella stessa cartella, vedrai che ti apre tutti i files in tab separate,
poi tramite il pulsante carichi sull'arduino mega

Il 27/lug/2016 19:13, "giangi007" notifications@github.com ha scritto:

Ciao Thomas, scusa se ti faccio perdere tempo, ma non ho capito come fare a
scaricare all'arduino mega tutti i file ino contenuti nel tuo file
Jarvin-master.

Grazie per il tuo aiuto

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ThomasAndreini/Jarvis/issues/5, or mute the thread
